service: typescript-serverless-starter

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  #Add your environment variables below
  environment:
    SAMPLE: sample
    SAMPLE_STRING: "sample environment variable string."

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths

custom:
  tscpaths:
    functions: functions
    modules: modules
    types: types
    utils: utils

functions:
  hello:
    handler: handler.hello
  sample:
    handler: functions/sample.handler
