service: typescript-serverless-starter

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths

package:
  include:
    - functions
    - modules
    - types

custom:
  tscpaths:
    functions: functions
    modules: modules
    types: types

functions:
  hello:
    handler: handler.hello
