service: typescript-serverless-starter

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  apiGateway:
    apiKeys:
      - typescript-serverless-starter-key-dev

plugins:
  - serverless-plugin-typescript
  - serverless-tscpaths

package:
  include:
    - functions
    - modules
    - types

custom:
  tscpaths:
    functions: functions
    modules: modules
    types: types

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: post
          private: true
          cors:
            origins:
              - "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: false
